<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Opera Framework - __APP_NAME__</title>
    <style type="text/css">
        *{
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            color: #656565;
        }
        html, body{
            margin: 0;
            padding: 0;
            background-color: #ededed;
        }
        h2{
            color: #fff;
        }
        .container{
            margin: auto;
            margin-top: 40px;
            width: 80%;
            min-width: 500px;
            max-width: 900px;
            background-color: #fff;
            box-shadow: 0 0 10px #b9b9b9;
        }
        .container header{
            background-color: #ff8f47;
            padding: 20px;
        }
        .container main{
            padding: 20px;
        }
        .panel{
            width: 100%;
            border: 1px solid #ccc;
            border-radius: 10px 10px 0 0;
        }
        .panel-heading{
            padding: 20px;
            border-radius: 10px 10px 0 0;
            color: #fff;
        }
        .panel-heading h2{
            margin: 0;
            padding:0 ;
        }
        .panel-body{
            padding: 20px;
        }

        .panel-danger .panel-heading{
            background-color: #d32d39;
        }
        .text-center{
            text-align: center;
            font-size: 10pt;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h2>The Opera Framework</h2>
        </header>
        <main>
            <h1>Welcome to your new Opera Framework project</h1>
        </main>
        <footer>
            <p class="text-center">
                The Opera Framework &copy; <?=date('Y')?>
            </p>
        </footer>
        
    </div>
</body>
</html>